const $=id=>document.getElementById(id);
const GEO="https://geocoding-api.open-meteo.com/v1/search";
const API="https://api.open-meteo.com/v1/forecast";
function text(c){return({0:"Clear sky",1:"Mainly clear",2:"Partly cloudy",3:"Overcast",45:"Fog",48:"Rime fog",51:"Light drizzle",53:"Drizzle",55:"Heavy drizzle",61:"Light rain",63:"Rain",65:"Heavy rain",71:"Light snow",73:"Snow",75:"Heavy snow",80:"Light rain showers",81:"Rain showers",82:"Heavy rain showers",95:"Thunderstorm",96:"Thunderstorm with hail",99:"Thunderstorm with heavy hail"}[c]||"Unknown conditions")}
async function coords(city){const r=await fetch(`${GEO}?name=${encodeURIComponent(city)}&count=1&language=en&format=json`);if(!r.ok)throw Error();const d=await r.json();if(!d.results?.length)throw Error();return d.results[0]}
async function getWeather(lat,lon){const q=new URLSearchParams({latitude:lat,longitude:lon,current:"temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m",daily:"weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,wind_speed_10m_max",timezone:"auto",forecast_days:"7"});const r=await fetch(`${API}?${q}`);if(!r.ok)throw Error();return r.json()}
function show(p,d){const c=d.current,x=d.daily;$("location-name").textContent=p.country?`${p.name}, ${p.country}`:p.name;$("updated").textContent=`Updated: ${new Date(c.time).toLocaleString()}`;$("temperature").textContent=`${Math.round(c.temperature_2m)}°C`;$("condition").textContent=text(c.weather_code);$("feels").textContent=Math.round(c.apparent_temperature);$("humidity").textContent=c.relative_humidity_2m;$("wind").textContent=Math.round(c.wind_speed_10m);$("rain").textContent=Number(c.precipitation).toFixed(1);$("forecast").innerHTML="";x.time.forEach((date,i)=>{const e=document.createElement("div");e.className="day";e.innerHTML=`<strong>${new Date(date+"T12:00:00").toLocaleDateString(undefined,{weekday:"short"})}</strong><p>${text(x.weather_code[i])}</p><p>${Math.round(x.temperature_2m_max[i])}° / ${Math.round(x.temperature_2m_min[i])}°</p><p>Rain: ${Number(x.precipitation_sum[i]).toFixed(1)} mm</p><p>Wind: ${Math.round(x.wind_speed_10m_max[i])} km/h</p>`;$("forecast").appendChild(e)});$("weather").classList.remove("hidden")}
async function search(city){$("status").textContent="Checking live weather...";try{const p=await coords(city);show(p,await getWeather(p.latitude,p.longitude));$("status").textContent=""}catch(e){$("status").textContent="Could not get weather. Check the city name and internet connection."}}
$("weather-form").addEventListener("submit",e=>{e.preventDefault();search($("city-input").value.trim())});
$("location-btn").addEventListener("click",()=>navigator.geolocation.getCurrentPosition(async p=>{try{show({name:"Your Location",country:""},await getWeather(p.coords.latitude,p.coords.longitude));$("status").textContent=""}catch(e){$("status").textContent="Could not get weather."}},()=>$("status").textContent="Location permission was denied."));
search("Bamenda");